# Automatically generated file. DO NOT MODIFY
#
# This file is generated by vendor/dolby/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/dolby/common

PRODUCT_COPY_FILES += \
    vendor/dolby/common/proprietary/vendor/etc/init/vendor.dolby.hardware.dms@2.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.dolby.hardware.dms@2.0-service.rc

PRODUCT_PACKAGES += \
    libdapparamstorage \
    vendor.dolby.hardware.dms@2.0 \
    libdeccfg \
    libstagefright_soft_ac4dec \
    libstagefright_soft_ddpdec \
    libswdap \
    libswgamedap \
    libswvqe \
    libdlbdsservice \
    vendor.dolby.hardware.dms@2.0-impl \
    manifest_vendor.dolby.hardware.dms.xml \
    vendor.dolby.hardware.dms@2.0-service
